name: sevenakini_mobile
description: "Sevenakini Mobile"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  device_preview: ^1.2.0
  device_preview_screenshot: ^1.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  riverpod_annotation: ^2.3.5
  sevenakini_shared: any
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.6

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env