include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
    
linter:
  rules:
    public_member_api_docs: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    always_put_required_named_parameters_first: false