name: Flutter CI

on:
  workflow_dispatch:

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" > .env
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Set up Melos
        uses: bluefireteam/melos-action@v3

      - name: Extract version from pubspec.yaml
        id: extract_version
        run: |
          VERSION=$(grep -o 'version:.*' apps/sevenakini_mobile/pubspec.yaml | awk '{print $2}')
          echo "version=${VERSION//\'/}" >> $GITHUB_ENV

      - name: Build Android APK
        uses: cedvdb/action-flutter-build-android@v1
        with:
          working-directory: ./apps/sevenakini_mobile
          keystore-base64: ${{ secrets.ANDROID_RELEASE_KEY }}
          keystore-password: "${{ secrets.ANDROID_RELEASE_KEY_PASSWORD }}"

      - name: Archive APK
        uses: actions/upload-artifact@v4.3.3
        with:
          name: release-apk
          path: apps/sevenakini_mobile/build/app/outputs/flutter-apk/app-release.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.version }}
          files: apps/sevenakini_mobile/build/app/outputs/flutter-apk/app-release.apk
          token: "${{ secrets.ACTIONS_TOKEN }}"
          fail_on_unmatched_files: true
          make_latest: true
